Controllers/EstoquesController.cs
using ControleEstoqueApp.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace ControleEstoqueApp.Controllers;

public class EstoquesController : Controller
{
    private readonly string apiUrl = "https://localhost:44320/api/ItemEstoques";

    //GET
    public async Task<ActionResult> Index()
    {
        List<ItemEstoques> ListaEstoques = new List<ItemEstoques>();

        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.GetAsync(apiUrl))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                ListaEstoques = JsonConvert.DeserializeObject<List<ItemEstoques>>(apiResponse);
            }
        }
        return View(ListaEstoques);
    }


    //GET{id}
    public ViewResult GetEstoque() => View();

    [HttpPost]
    public async Task<IActionResult> GetEstoque(int id)
    {
        ItemEstoques estoque = new ItemEstoques();

        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.GetAsync(apiUrl + "/" + id))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                estoque = JsonConvert.DeserializeObject<ItemEstoques>(apiResponse);
            }

        }
        return View(estoque);
    }

    //POST
    public ViewResult AddEstoque() => View();

    [HttpPost]
    public async Task<IActionResult> AddEstoque(ItemEstoques estoque)
    {
        ItemEstoques estoqueAdd = new ItemEstoques();

        using (var httpClient = new HttpClient())
        {
            StringContent content = new StringContent(JsonConvert.SerializeObject(estoque), Encoding.UTF8, "application/json");

            using (var response = await httpClient.PostAsync(apiUrl, content))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();

                estoqueAdd = JsonConvert.DeserializeObject<ItemEstoques>(apiResponse);
            }
        }
        return View(estoqueAdd);
    }

    //PUT




    [HttpGet]
    public async Task<IActionResult> UpdateEstoque(int id)
    {
        ItemEstoques estoque = new ItemEstoques();

        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.GetAsync(apiUrl + "/" + id))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                estoque = JsonConvert.DeserializeObject<ItemEstoques>(apiResponse);
            }
        }
        return View(estoque);
    }


    [HttpPost]
    public async Task<IActionResult> UpdateEstoque(ItemEstoques estoque)
    {
        ItemEstoques UpdateEstoque = new ItemEstoques();

        using (var httpClient = new HttpClient())
        {

            var content = JsonContent.Create<ItemEstoques>(estoque);

            using (var response = await httpClient.PutAsync(apiUrl, content))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                ViewBag.Result = "Sucesso";
                UpdateEstoque = JsonConvert.DeserializeObject<ItemEstoques>(apiResponse);
            }
        }

        return View(UpdateEstoque);
    }


    //DELETE
    [HttpPost]
    public async Task<IActionResult> DeleteEstoque(int Id)
    {
        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.DeleteAsync(apiUrl + "/" + Id))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
            }
        }
        return RedirectToAction("Index");
    }

}

Controllers/LojasController.cs
using ControleEstoqueApp.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace ControleEstoqueApp.Controllers;

public class LojasController : Controller
{
    private readonly string apiUrl = "https://localhost:44320/api/Lojas";

    //GET
    public async Task<ActionResult> Index()
    {
        List<Loja> ListaLojas = new List<Loja>();

        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.GetAsync(apiUrl))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                Console.WriteLine(apiResponse);
                ListaLojas = JsonConvert.DeserializeObject<List<Loja>>(apiResponse);
            }
        }
        return View(ListaLojas);
    }

    //GET{id}
    public ViewResult GetLoja() => View();
    [HttpPost]
    public async Task<IActionResult> GetLoja(int id)
    {
        Loja loja = new Loja();

        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.GetAsync(apiUrl + "/" + id))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                loja = JsonConvert.DeserializeObject<Loja>(apiResponse);
            }

        }
        return View(loja);
    }

    //POST
    public ViewResult AddLoja() => View();

    [HttpPost]
    public async Task<IActionResult> AddLoja(Loja loja)
    {
        Loja lojaAdd = new Loja();

        using (var httpClient = new HttpClient())
        {
            StringContent content = new StringContent(JsonConvert.SerializeObject(loja), Encoding.UTF8, "application/json");

            using (var response = await httpClient.PostAsync(apiUrl, content))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();

                lojaAdd = JsonConvert.DeserializeObject<Loja>(apiResponse);
            }
        }
        return View(lojaAdd);
    }

    //PUT
    [HttpGet]
    public async Task<IActionResult> UpdateLoja(int id)
    {
        Loja loja = new Loja();

        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.GetAsync(apiUrl + "/" + id))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                loja = JsonConvert.DeserializeObject<Loja>(apiResponse);
            }
        }
        return View(loja);
    }
    [HttpPost]
    public async Task<IActionResult> UpdateLoja(Loja loja)
    {
        Loja UpdateLoja = new Loja();

        using (var httpClient = new HttpClient())
        {

            var content = JsonContent.Create<Loja>(loja);

            using (var response = await httpClient.PutAsync(apiUrl, content))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                ViewBag.Result = "Sucesso";
                UpdateLoja = JsonConvert.DeserializeObject<Loja>(apiResponse);
            }
        }

        return View(UpdateLoja);
    }





    //DELETE
    [HttpPost]
    public async Task<IActionResult> DeleteLoja(int LojaId)
    {
        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.DeleteAsync(apiUrl + "/" + LojaId))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
            }
        }
        return RedirectToAction("Index");
    }

}

Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ControleEstoqueApp.Models;
using System.Text;

namespace ControleEstoqueApp.Controllers;

public class ProdutosController : Controller
{
    private readonly string apiUrl = "https://localhost:44320/api/Produtos";

    //GET
    public async Task<ActionResult> Index()
    {
        List<Produto> ListaProdutos = new List<Produto>();

        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.GetAsync(apiUrl))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                Console.WriteLine(apiResponse);
                ListaProdutos = JsonConvert.DeserializeObject<List<Produto>>(apiResponse);
            }
        }
        return View(ListaProdutos);
    }

    //GET{id}
    public ViewResult GetProduto() => View();
    [HttpPost]
    public async Task<IActionResult> GetProduto(int id)
    {
        Produto produto = new Produto();

        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.GetAsync(apiUrl + "/" + id))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                produto = JsonConvert.DeserializeObject<Produto>(apiResponse);
            }

        }
        return View(produto);
    }

    //POST
    public ViewResult AddProduto() => View();

    [HttpPost]
    public async Task<IActionResult> AddProduto(Produto produto)
    {
        Produto produtoAdd = new Produto();

        using (var httpClient = new HttpClient())
        {
            StringContent content = new StringContent(JsonConvert.SerializeObject(produto), Encoding.UTF8, "application/json");

            using (var response = await httpClient.PostAsync(apiUrl, content))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();

                produtoAdd = JsonConvert.DeserializeObject<Produto>(apiResponse);
            }
        }
        return View(produtoAdd);
    }

    //PUT
    [HttpGet]
    public async Task<IActionResult> UpdateProduto(int id)
    {
        Produto produto = new Produto();

        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.GetAsync(apiUrl+"/"+id))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                produto = JsonConvert.DeserializeObject<Produto>(apiResponse);
            }
        }
        return View(produto);
    }
    [HttpPost]
    public async Task<IActionResult> UpdateProduto(Produto produto)
    {
        Produto UpdateProduto = new Produto();

        using (var httpClient = new HttpClient())
        {
            //var content = new MultipartFormDataContent();
            var content = JsonContent.Create<Produto>(produto);
            //content.Headers.Add("Access-Control-Allow-Origin", "*");
            //content.Add(new StringContent(produto.ProdutoId.ToString()), "ProdutoId");
            //content.Add(new StringContent(produto.Nome.ToString()), "Nome");
            //content.Add(new StringContent(produto.Preco.ToString()), "Preco");
            //content.Add(new StringContent(produto.DataCadastro.ToString()), "DataCadastro");

            using (var response = await httpClient.PutAsync(apiUrl, content))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
                ViewBag.Result = "Sucesso";
                UpdateProduto = JsonConvert.DeserializeObject<Produto>(apiResponse);
            }
        }

        return View(UpdateProduto);
    }


    //DELETE
    [HttpPost]
    public async Task<IActionResult> DeleteProduto(int ProdutoId)
    {
        using (var httpClient = new HttpClient())
        {
            using (var response = await httpClient.DeleteAsync(apiUrl + "/" + ProdutoId))
            {
                string apiResponse = await response.Content.ReadAsStringAsync();
            }
        }
        return RedirectToAction("Index");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProdutoEstoqueWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProdutoEstoqueWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Index">Lojas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estoques" asp-action="Index">Estoques</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProdutoEstoqueWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_estoquesLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link asp-href-include="lib/bootstrap/dist/css/*.min.css" rel="stylesheet" />
        <meta charset="utf-8" />
        <title>@ViewData["Title"] - ProdutoEstoqueWeb</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ProdutoEstoqueWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Index">Lojas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estoques" asp-action="Index">Estoques</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_exibeProdutos.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

@{
    ViewData["Title"] = "_exibeProdutos";
    Layout = "~/Views/Shared/_produtosLayout.cshtml";
}


</head>


<body>


<h1>_exibeProdutos</h1>



<div class="modal fade" id="exibeProdutos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Detalhe do estoque</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table table-sm table-striped table-bordered m-2">
                    <thead>
                        <tr>
                            <td>Id do Produto</td>
                            <td>Nome do Produto</td>
                            <td>Quantidade Disponivel</td>
                        </tr>
                    </thead>
                    <tbody>
                    <td>10</td>
                    <td>Caneta</td>
                    <td>300</td>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>



</body>

Views/Shared/_lojasLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link asp-href-include="lib/bootstrap/dist/css/*.min.css" rel="stylesheet" />
        <meta charset="utf-8" />
        <title>@ViewData["Title"] - ProdutoEstoqueWeb</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/ProdutoEstoqueWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Index">Lojas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estoques" asp-action="Index">Estoques</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_produtosLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link asp-href-include="lib/bootstrap/dist/css/*.min.css" rel="stylesheet" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - ProdutoEstoqueWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProdutoEstoqueWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Index">Lojas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estoques" asp-action="Index">Estoques</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        @RenderBody()
    </div>
</body>
</html>